
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://jasllsaj.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl:

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Jason Lai"
title: "{ Jason Lai }"
description: "Blog and website of John Smith, blogging mainly for tech. Opinions expressed are mine."
keywords: "lai, jason, personal, jekyll, theme"
favicon: "/img/robot.ico"

################
# Header layout #
################

black-favicon: 
logo:

background-img: "../img/sydney-bg.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Fourth year Mechatronics and Science student @ Sydney University"
  - text: "Diligent. Results-driven. Ready to make a difference."

me-img: "/img/2019.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

############
# Timeline #
############

events:
  - image: "/img/timeline/usyd.png"
    date: "February 2019 - December 2023"
    description: "Studying Mechatronics and Science with majors in Space Engineering and Chemistry. <a href=\"javascript:;\" id=\"uni\">See my prizes and scholarships.</a>"
  - image: "/img/timeline/JFC.jpg"
    date: "June 2022 - July 2022"
    description: "Interned at Jacaranda Flame Consulting. Developed software on top of the Tekla Structures Open API to <b>automate 3D modelling for a client</b>. Subject to non-disclosure agreement."
  - image: "/img/timeline/control.png"
    date: "February 2021 - July 2022"
    description: "Tutored introductory Python (ENGG1810/INFO1110) and control engineering (AMME3500) units at Sydney University."
  - image: "/img/timeline/acfr.png"
    date: "December 2021 - February 2022"
    description: "Completed a research internship at the Australian Centre for Field Robotics to devise <b>data-driven algorithms for calibrating a 3D hyperspectral camera</b>. <a href=\"javascript:;\" id=\"hyperspectral\">See photos.</a>"
  - image: "/img/timeline/yumi.jpg"
    date: "December 2020 - February 2021"
    description: "Completed a research internship at Sydney University to <b>design algorithms for automating pick-and-place tasks</b> using a Yumi ABB dual-arm robot, and <b>Python APIs for MoveIt! and OpenCV</b>.
    I helped <b>pair-program</b> the algorithm, which demonstrated robust detection, stacking and disassembly of 30 Jenga blocks in a tower. <a href=\"javascript:;\" id=\"yumi\">See it in action.</a>"
  - image: "/img/timeline/sumo.jpg"
    date: "October 2020"
    description: "Awarded an honourable mention in Sydney University Mechatronics Organisation's Hackathon for my <b>strong systems-thinking mindset</b>. Prototyped a wearable device that provides audio prompts to improve in-store navigation."
  - image: "/img/timeline/zhangs.png"
    date: "November 2018 - December 2019"
    description: "Tutored Physics and Chemistry at Zhang's HSC Coaching."
  - image: "/img/timeline/leukaemia.jpg"
    date: "October 2019"
    description: "Volunteered at events including Burwood Festival and Leukaemia Foundation's Light the Night."
  - image: "/img/timeline/jrahs.jpg"
    date: "December 2018"
    description: "Graduated as Dux of James Ruse Agricultural High School. <a href=\"javascript:;\" id=\"school\">See my achievements.</a>"
  - image: "/img/timeline/maths.png"
    date: "February 2017 - September 2018"
    description: "Taught <b>voluntary maths mentoring classes</b> before school and during lunches."
  - image: "/img/timeline/doe.jpg"
    date: "April 2015 - March 2017"
    description: "Achieved Bronze and Silver Duke of Edinburgh Awards"

# First image of the Timeline
timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb:
author_blurb_image:

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/js0nlai"
  - title: "github"
    url: "https://github.com/js0n-lai"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/js0n-lai"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
